### PR TITLE
Feature/more definitions

### PR DESCRIPTION
**Pull request by dcuddeback**
This PR contains the definitions that are needed by IOKit. It also changes the types for `mach_port_t` and `thread_t` and changes the `kern_return_t` values from static to const.

### CODE REVIEW

**Comment by fitzgen** [comment]
Awesome :)

**Comment by fitzgen** [comment]
Added you as an author to Cargo.toml (not sure if that grants you permissions to publish to crates.io or not) and published 0.0.3 with all your latest changes.

**Comment by fitzgen** [comment]
Alright, you should be an owner on crates.io now, too. Congrats! Thanks!

**Comment by dcuddeback** [comment]
@fitzgen Awesome. Thank you! I can confirm that I see mach included in my list of crates on crates.io. Thanks for creating this in the first place. :)

**Pull request merged**
