### PR TITLE
Feature/rustup

### PR DESCRIPTION
**Pull request by dcuddeback**
This PR contains changes necessary to make the mach crate compile on Rust 1.0.0 stable. I also moved the `dump_process_registers.rs` binary to `examples`, so that it runs with `cargo test` instead of `cargo build`. Not sure if you agree with that. I figured there's no reason to build the binary when using `mach` as a library. Let me know if you disagree and I'd be happy to move it back.

### CODE REVIEW

**Comment by dcuddeback** [comment]
Looks like Travis is running this on a Linux container, which doesn't have mach.

**Comment by fitzgen** [comment]
Awesome, thanks!

Are you interested in maintaining (or helping to maintain) this crate? I just put it together while I was playing around with some stack walking code, and as you can see, I haven't been doing a great maintenance job.

I also noticed the issues with Travis running linux, and I'm not sure how to work around it. I suppose we can just remove the Travis hooks if there isn't a workaround.

**Comment by fitzgen** [comment]
Filed https://github.com/fitzgen/mach/issues/3 for the travis issues

**Comment by dcuddeback** [comment]
@fitzgen Thanks for the quick response. I'd be happy to help maintain the crate.

**Comment by fitzgen** [comment]
Thanks! Adding you as a collaborator!

**Pull request merged**
