### PR TITLE
Make fields of thread status public.

### LINKED ISSUE #35: Make fields of thread state struct public
The fields of the public struct x86_thread_state64_t should be public so that the user can access them.

Example code:
```rust
use mach::structs::x86_thread_state64_t;
use mach::thread_act::thread_get_state;
use mach::thread_status::{x86_THREAD_STATE64, thread_state_t};

let thread_state = x86_thread_state64_t::new();
let thread_state_p = &mut x86_thread_state64_t as *mut x86_thread_state64_t;
let result = unsafe {thread_get_state(some_thread, x86_THREAD_STATE64, thread_state_p as thread_state_t, &mut new_state_count)};
// Should be able to get the instruction pointer by doing:
let rip = unsafe{ thread_state.rip };

// Currently, get the below error message
// -> field `__rip` of struct `mach::structs::x86_thread_state64_t` is private
```

I think simply making the fields public is the right option for this library given that it tries to be a low-level wrapper around the system headers.

### PR DESCRIPTION
**Pull request by codimension**
Fixes #35.

### CODE REVIEW

**Comment by gnzlbg** [comment]
This should have been caught by ctest, but wasn't. I thought this might be because the header where this struct is defined is not being verified, but that does not appear to be the case. 

This struct should be in the `thread_status.h` header, and that's properly checked here: https://github.com/fitzgen/mach/blob/master/mach-test/build.rs#L113

**Comment by gnzlbg** [comment]
The CI breakage is because the ctest crate broke its API. I've notified them so that they do a semver release and fixed this in #37 . Once the tests pass there I'll merge and re-run the tests here.

In the meantime, we need to fix the `ctest` suite to catch this before fixing this.

**Comment by gnzlbg** [comment]
So i've investigated a bit more and it seems that ctest doesn't check that the struct values are public, it just checks that the names match and that the ABI is correct. Once CI is green I'll merge this. I have another PR updating the mach version to 0.2 that should land afterwards, at which point I'll publish the 0.2.1 version of the crate so that you can use this.

**Comment by gnzlbg** [comment]
Thanks!

**Comment by codimension** [comment]
Cheers, you’ve just merged my first pr!

**Comment by gnzlbg** [comment]
@bythebook mach 0.2.2 is published and contains this change, thanks again!

**Pull request merged**
