### PR TITLE
Add mach_thread_self, thread_suspend, and thread_resume

### LINKED ISSUE #41: Implement more thread related api
For use in https://github.com/servo/servo/pull/21673, I would be interested in adding the following functions:

1. `mach_thread_self`
2. `thread_suspend`
3. `thread_resume`

Could you please share a rough outline of how I would go about it?

### PR DESCRIPTION
**Pull request by gterzian**
FIX #41

### CODE REVIEW

**Comment by gterzian** [comment]
From local testing, this seems to work, however I couldn't find online the proper location for those functions, so I've tentatively put them in `thread_act`. 

Please also advise on the CI failures, which appear unrelated...

**Review by gnzlbg — CHANGES_REQUESTED** [review]
`thread_suspend` and `thread_resume` are in `thread_act.h` (https://github.com/phracker/MacOSX-SDKs/blob/9fc3ed0ad0345950ac25c28695b0427846eea966/MacOSX10.9.sdk/usr/include/mach/thread_act.h ) but `mach_thread_self` goeas in `mach_init.h` (https://github.com/phracker/MacOSX-SDKs/blob/9fc3ed0ad0345950ac25c28695b0427846eea966/MacOSX10.12.sdk/usr/include/mach/mach_init.h)

**Comment by gnzlbg** [comment]
> Please also advise on the CI failures, which appear unrelated...

I've sent a PR that fixes most of them and restarted the build (some will still be failing though), but don't worry much about these. I'll fix them after merging this :)

**Comment by gterzian** [comment]
Thanks for the pointers, and ready for review.

**Review by gnzlbg — APPROVED** [review]
LGTM, thanks!

**Comment by gnzlbg** [comment]
The FFI ABI tests are failing, I think it's because one has to import the new `mach_init` module in `mach-test/test/main.rs` :)

**Comment by gterzian** [comment]
Thanks, let's see what it does now(I don't have Xcode installed and it seems I can't run those locally)

**Comment by gnzlbg** [comment]
Looking good! I'll merge when CI finishes. I'll update some other stuff in mach and release a new version later today.

**Comment by gterzian** [comment]
Thanks!

**Comment by gnzlbg** [comment]
Thank you!

**Comment by gnzlbg** [comment]
@gterzian i've done a release (0.2.3) that contains these changes, thank you again!

**Comment by gterzian** [comment]
@gnzlbg great, thanks for the release!

**Pull request merged**
